### ISSUE TITLE
Differences between CVAE and MD-CVAE

### ISSUE THREAD

**Issue by enoche** [yaochenzhu/MD-CVAE#1]
Hi, thanks for sharing the code for this paper.

May I have your help to identify the major differences between CVAE and MD-CVAE, as CVAE also ingest item-content for CF.
However, in your experiment, CAVE is compared without item-content?

The general idea and formula seems same between the two papers at my first glance.

https://github.com/eelxpeng/CollaborativeVAE
@eelxpeng 

Thanks.

**Comment by yaochenzhu** [comment]
Hi, thanks for asking!

The answer is that CVAE uses MF as the CF backbone, (1) which is shallow and (2) the inference for new users has high computational cost. MD-CVAE uses Multi-VAE (UAE) as the CF backbone by viewing the first and last layer weights as item embeddings. Therefore, MD-CVAE can model user in a deeper manner. In addition, we also propose a symmetric inference strategy to increase the efficiency to make inference for new users facing cold-start items.

In essence, MD-CVAE exploits the strengths of Multi-VAE and CVAE to address each other's weaknesses, which successfully solves the inherent sparsity and cold-start problems of existing UAE-based recommenders, and the shallow user modeling and inefficient inference of existing MF-based methods (such as CVAE).

Moreover, in introducing the mutual regularization (right before Eq 4), we properly cite the CVAE paper, although such  a tightly coupling strategy originated from the CTR paper and pass from CTR to CDL to CVAE.

As for the experiment, we do use item content for CVAE. Otherwise we cannot compare the cold-start item recommendation performance among MD-CVAE, CVAE, CDL and CTR.

I hope this can make our paper more clear, and I'm sorry for the confusion.

Best,
Yaochen

**Comment by enoche** [comment]
Okay, thanks. Your explanation helps.
