### ISSUE TITLE
Meaning of datasets

### ISSUE THREAD

**Issue by enoche** [yaochenzhu/MD-CVAE#2]
Hi, May I have your kind help to identify the meanings of each file of a dataset used in your code (e.g. cora):
As normally, we only need the adj matrix (user-item graph) and the item feature files for VAE.

- item_features.npz
- meta.csv
- train.csv
- *_obs.csv
- *_unk.csv
- *_X.csv
- *_Y.csv

Thanks a lot.

**Comment by yaochenzhu** [comment]
Hi, sure! Thanks for asking!

First, please note that our experiments are conducted in the so-called "strong generalization" setting, as described in the  Multi-VAE paper. This means that we split the users into train, val, and test sets by the ratio 8:1:1. The historical ratings of training users are assumed to be fully observed (train.csv), which is used to train the model. As for val and test users, we assume (as with the Multi-VAE paper) that 80% of the interactions are observed (val_obs.csv, test_obs.csv). The observed interactions can be used to infer the user embeddings given a trained model, which can then be fed into the decoder to make predictions. Finally, we compare the val prediction with the unobserved interactions of val users (val_unk.csv) to select the model, and with the final model selected by the val users, we make predictions for the test user and compare them with the unobserved interactions of test users (test_unk.csv) for model evaluation and report the results in the paper. The _X.npz, _Y.npz files are just processed sparse matrices of the corresponding csv files for more efficient reuse; otherwise, if you'd like to re-run the experiments, you'll have to process the csv from scratch, which is time-consuming.

I hope the above answers can help with your confusion.

Best,
Yaochen

**Comment by enoche** [comment]
Thanks for your comments. One more question:

> As for val and test users, we assume (as with the Multi-VAE paper) that 80% of the interactions are observed (val_obs.csv, test_obs.csv). 

As your experiments are inline with Multi-VAE, which means that the val/test users are held-out and never appear in training dataset, am I right?

**Comment by yaochenzhu** [comment]
> 

Yeah, absolutely! We only use the assumed observed interaction of validation and test users to infer the user embedding, and this won't change the weights of the network.

**Comment by enoche** [comment]
Okay. Thanks for your feedback.

How about the performance if we put the observed interactions of val/test users to training, and validated and tested only on unobserved interactions. In this way, we can also get the user embedding, right?  Does this setting would increase the performance, say, we have more data in training?

**Comment by yaochenzhu** [comment]
> 

Yeah, this is close to the so called "Weak Generalization" setting by the authors of Multi-VAE, where for each user we assume parts of the interactions as observed, and we aim to predict the interactions with the remaining items. 
 
I think that the reason why we need our recommendation model to be able to do strong generalization (or why the authors of Multi-VAE paper invent such a setting) is because sometimes the model training can be laborious and time-consuming. And the strong generalization ability ensures the model be able to make predictions for new users even if these users did not appear in the training set. So it basically reduces the model retraining frequency.

**Comment by enoche** [comment]
> the model be able to make predictions for new users even if these users did not appear in the training set.

This setting is not common but also make sense. 
Common setting would be most test/val users have history interactions in training.
It would be better to report the performance on both settings. Multi-VAE only report the 'Strong' setting.

**Comment by yaochenzhu** [comment]
Indeed! Thank you for your suggestions for the improvements of our work.

**Comment by enoche** [comment]
Thanks for your feedback, nice to talk with you.
